apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::860380375890:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-M80J74JHIPHG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::860380375890:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T21:07:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1642"
  uid: 87ef559a-ae6e-42eb-a389-1f162881e321
